language: swift
osx_image: xcode10

before_install:
  - pod repo update
  - git submodule update --init --recursive

script:
  - set -o pipefail && xcodebuild -scheme CodeChallenge -workspace CodeChallenge.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0' -destination 'platform=iOS Simulator,name=iPad Air 2,OS=11.4' -disable-concurrent-destination-testing build test | bundle exec xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)